### ISSUE TITLE
`filepath` option should be set on mdx options object

### ISSUE THREAD

**Issue by joeljeske** [elemental-design/rollup-plugin-mdx#1]
`mdx(content, options)` should set `filepath` property on the options object. This is to enable plugins that read metadata about the file. 

https://github.com/mdx-js/mdx/blob/master/packages/mdx/index.js#L120-L123

**Comment by macintoshhelper** [comment]
Sorry, I missed this issue! Would this code resolve it?

https://github.com/elemental-design/rollup-plugin-mdx/blob/master/src/index.js#L20

```js
    transform(content, filename) {
      if (!ext.test(filename) || !filter(filename)) {
        return null;
      }

      const opts = Object.assign({}, options, {
        filepath: path.resolve(filename),
      })

      return mdx(content, opts).then((result) => {
```

**Comment by joeljeske** [comment]
Yup that’s similar to what I have patched.

 I might think, however, that it would be better to allow “options” to come as the 3rd argument as to allow the user to explicitly set a file path if desired, but defaulting to the passed in file name.

**Comment by macintoshhelper** [comment]
~Would this work?~

```
      const opts = Object.assign({}, options, {
        filepath: options.filepath || path.resolve(filename),
      })
```


Ah, is this what you meant?

```js
      const opts = Object.assign({}, {
        filepath: path.resolve(filename)
      }, options);
```

**Comment by joeljeske** [comment]
Sounds great to me

**Comment by macintoshhelper** [comment]
~Could you test `rollup-plugin-mdx@0.1.0-alpha.0` please? I've opened a PR~

Can you check that the PR/`rollup-plugin-mdx@0.1.0-alpha.2` resolves this issue please? I'll publish a new version once it's merged. Thanks!

**Comment by joeljeske** [comment]
Yup! Works great. Thank you!

**Comment by macintoshhelper** [comment]
Great, thanks for reporting the issue! I've merged to master and will publish an update to `npm` soon (going to work on a middleware option also), and am watching repo activity now 🙂
