### ISSUE TITLE
Support sourcemaps

### ISSUE THREAD

**Issue by mariusGundersen** [elemental-design/rollup-plugin-mdx#5]
It would be great if the transformation included the sourcemap back to the original source.

**Comment by macintoshhelper** [comment]
Is this something that's supported by the original Webpack loader? (through Babel). Ideally, I'd like to maintain feature parity with the Webpack loader.

**Comment by macintoshhelper** [comment]
If this is supported by the `mdx` Webpack loader, I could have a go supporting it, I'm not really sure on a test case to check that it works, as I haven't used sourcemaps with `mdx` before.

I could pass `{ sourceMaps: true }` to Babel core, unless it has to be inline? And I can't find an easy, dependency-free way of getting access to Rollup's `sourceMap` option, I can't find an example: https://github.com/rollup/rollup/issues/1583

https://babeljs.io/docs/en/options#sourcemaps

**Comment by mariusGundersen** [comment]
I had a quick look into this and it seems like mdx does not support sourcemaps yet, so there isn't much you can do about it either. I will look into getting sourcemaps into mdx.

**Comment by macintoshhelper** [comment]
> I will look into getting sourcemaps into mdx.

Great, if you create an issue in `mdx`, please comment a link to it here so I can keep track of it. I'll close this issue for now, but feel free to reopen (if you have privileges), or tag me here to reopen it once there's a path/test-case for implementing it here 🙂.
